name: GitHub Actions
run-name: Action is going ON
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
        name: Your Node Application ready to go
      - run: npm install
      - run: npm run test

      - name: Run a sample github actions
        run: echo "This workflow runs successfully"
