name: GitHub Actions
run-name: ${{github.actor}} learning github actions
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node}}
      - name: Your Node Application ready to go
      - run: npm install
      - run: npm start

      - name: Run a sample github actions
        run: echo "This workflow runs successfully"
